// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNywAcYUIVhi6BjnEaeNgeYWtXJnYD9QE',
    appId: '1:443845042528:web:530a00e3dbec2f0243be05',
    messagingSenderId: '443845042528',
    projectId: 'database-3d070',
    authDomain: 'database-3d070.firebaseapp.com',
    storageBucket: 'database-3d070.appspot.com',
    measurementId: 'G-YZGCQHWQ1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoc3fwBJxMen4as1etZd6oiOy8HNXcAec',
    appId: '1:443845042528:android:0974b04b133d6da843be05',
    messagingSenderId: '443845042528',
    projectId: 'database-3d070',
    storageBucket: 'database-3d070.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0O_RCXpi8XIek-zfTpZ80stNv4RwMStg',
    appId: '1:443845042528:ios:84626ff66d554cb343be05',
    messagingSenderId: '443845042528',
    projectId: 'database-3d070',
    storageBucket: 'database-3d070.appspot.com',
    iosBundleId: 'com.example.vansaquatic',
  );
}
